import { useSelector } from 'react-redux';
import getEstimation from '../util/PanelCalculator';
import { Box, Paper, Typography } from '@mui/material';
import { Device } from './Device';
import "./css/TeslaMegapackStyles.css";

// The UI should also have an autogenerated layout showing an arrangement of batteries based on the user’s configuration

const PlanLayoutPanel = () => {
    const battery = useSelector((state: any) => state.battery);
    const noOfBatteries = battery.noOfBatteries;

    const estimation = getEstimation(battery, noOfBatteries);

    //Improvement to take ratio of width and height to adjust preview
    // const width = battery.batteryFloorWidth;
    // const height = battery.batteryFloorHeight;

    return (
        <>
            <Box m={2}>
                <Typography variant="h6" gutterBottom>
                    {"Preview Of Site"}
                </Typography>
                <Paper elevation={3} variant="outlined">
                    <Box display="flex" flexWrap="wrap" >
                        <Device deviceName={battery.batteryType} noOfDevices={noOfBatteries} />
                        <Device deviceName={"Transformer"} noOfDevices={estimation.noOfTransformers} />
                    </Box>
                </Paper>
            </Box>
        </>
    );
}

export default PlanLayoutPanel;